services:
  - type: web
    name: calendario-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Lucky010220Kiana@db.hjaoqfvrrkqywxooevlb.supabase.co:5432/postgres
      - key: NODE_VERSION
        value: 18