services:
  - type: web
    name: calendario-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run migrate && npm run start
    envVars:
      - key: NODE_VERSION
        value: 18